# CI Test - Build the action container
# build test container which has default test files and validate
name: CRDA scan Python Example
on: [ push, workflow_dispatch ]
jobs:
  test:
    runs-on: ubuntu-latest
    name: Analyse Python project
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: kubernetes-client/python

      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'

      - run: |
          pip install --target=site-dir -r requirements.txt
          
      - name: Install CRDA
        uses: redhat-actions/openshift-tools-installer@v1
        with:
          source: github
          github_pat: ${{ github.token }}
          crda: "latest"

      - name: CRDA Scan
        uses: divyansh42/crda-action@main
        with:
          manifest_file_path: requirements.txt
          pkg_installation_directory_path: site-dir
          crda_key: ${{ secrets.CRDA_KEY }}
          # snyk_token: ${{ secrets.SNYK_TOKEN }}
          consent_telemetry: true

      - name: Print Analysis Report
        run: cat crda_analysis_report.json
