name: CRDA scan Node Example
on: [ push, workflow_dispatch ]
jobs:
  test:
    runs-on: ubuntu-20.04
    name: Analyse Node project
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
        with:
          # repository: nodejs/examples
          repository: jduimovich/crda-sarif-poc

      - name: Checkout action
        uses: actions/checkout@v2
        with:
          path: crda

      - name: Install npm
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: |
          ls
          npm install

      - name: Install CRDA
        uses: redhat-actions/openshift-tools-installer@v1
        with:
          source: github
          github_pat: ${{ github.token }}
          crda: "latest"

      - name: CRDA Scan
        id: scan
        uses: ./crda
        with:
          manifest_file_path: package.json
          crda_key: ${{ secrets.CRDA_KEY }}
          # snyk_token: ${{ secrets.SNYK_TOKEN }}
          analysis_report_file_name: node
          consent_telemetry: true
          fail_on_vulnerability: "error"

      - name: Print Analysis Report
        if: ${{ always() && steps.scan.outputs.crda_report_json }}
        run: cat ${{ steps.scan.outputs.crda_report_json }}

      - name: Print Sarif
        if: ${{ always() && steps.scan.outputs.crda_report_sarif }}
        run: cat ${{ steps.scan.outputs.crda_report_sarif }}

      - name: Print Report Link
        run: echo ${{ steps.scan.outputs.report_link }}

      - name: Upload result to GitHub Code Scanning
        if: ${{ steps.scan.outputs.crda_report_sarif }}
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: ${{ steps.scan.outputs.crda_report_sarif }}

      - name: Save intermediate files
        run: |
          mkdir -p uploads
          mv ${{ steps.scan.outputs.crda_report_json }} uploads
          mv ${{ steps.scan.outputs.crda_report_sarif }} uploads

      - name: Upload merged Results
        uses: actions/upload-artifact@v2
        with:
          name: workfiles_node
          path: ./uploads
