# Template workflow for OpenShift GitHub Connector

name: Scan with CodeReady Dependency Analytics

on:
  # https://github.com/redhat-actions/crda/#scanning-pull-requests
  push:
    branches: [ "n/a" ]

jobs:
  crda-scan:
    name: Scan with CodeReady Dependency Analytics
    runs-on: ubuntu-20.04

    steps:
    - name: Set up environment
      # May use setup-[go|java|node|python]
      uses: actions/setup-node@v2

      # https://github.com/redhat-actions/openshift-tools-installer
    - name: Install CRDA
      uses: redhat-actions/openshift-tools-installer@v1
      with:
        source: github
        github_pat: ${{ github.token }}
        crda: latest

      # https://github.com/redhat-actions/crda/
    - name: CRDA Scan
      # TODO - v1
      uses: redhat-actions/crda@v1
      with:
        crda_key: ${{ secrets.CRDA_KEY }}
